<a href="https://colab.research.google.com/github/Ashithajaina/internship/blob/master/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
>>> a = np.array([[1.0, 2.0], [3.0, 4.0]])
>>> print(a)

[[1. 2.]
 [3. 4.]]


In [2]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [3]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [9]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
j

   

array([[ 0., -1.],
       [ 1.,  0.]])

In [10]:
j @j

array([[-1.,  0.],
       [ 0., -1.]])

In [7]:
np.trace(u)

2.0