<a href="https://colab.research.google.com/github/Ashithajaina/internship/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x=2
x*7

14

In [9]:
 import numpy as np
 a = np.arange(15).reshape(3, 5)
 a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
np.__version__

'1.16.4'

In [7]:
a.dtype.name

'int64'

In [10]:
a.itemsize

8

In [11]:
a.size


15

In [12]:
type(a)

numpy.ndarray

In [14]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [15]:
type(b)

numpy.ndarray

In [24]:
import numpy as np
a = np.arange(30).reshape(2, 5, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [25]:
a.shape

(2, 5, 3)

In [26]:
a.ndim

3

In [27]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [29]:
import numpy as np
>>> a = np.array([2.1,3.0,4.2])
>>> a

array([2.1, 3. , 4.2])

In [30]:
a.dtype

dtype('float64')

In [28]:
a.dtype

dtype('int64')

In [0]:
a = np.array([1,2,3,4]) 

In [34]:
b = np.array([(1.5,2,3), (4,5,6)])
>>> b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [35]:
b = np.array([(1.5,2,3), (4,5,6), (2,3,4)])
>>> b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [2. , 3. , 4. ]])

In [36]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
>>> c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [43]:
np.zeros( (3,4) )


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [45]:
np.arange( 0, 2, 0.3 )                 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [46]:
np.arange( 0, 2, 0.3 )                 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [47]:
from numpy import pi
>>> np.linspace( 0, 2, 9 ) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [48]:
a = np.arange(6)                         
print(a)


[0 1 2 3 4 5]


In [49]:
 print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
