<a href="https://colab.research.google.com/github/Ashithajaina/internship/blob/master/slicing2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
B = np.arange(3)
B

array([0, 1, 2])

In [4]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [11]:
b = np.array([9, 16, 4])
np.sqrt(b)

array([3., 4., 2.])

In [8]:
np.sqrt(b)

array([1.41421356, 1.        , 2.        ])

In [12]:
a = np.arange(10)**3
>>> a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [13]:
a[2]

8

In [14]:
a[4:10:2]

array([ 64, 216, 512])

In [15]:
for i in a:
...     print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [33]:
 a = np.array([[(1,2,3)],[(4,5,6)],[(5,6,7)],[(3,4,5)]])
>>> a

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[5, 6, 7]],

       [[3, 4, 5]]])

In [21]:
a.ndim



3

In [40]:
a[1:2:1]

array([[[4, 5, 6]]])

In [41]:
a[-1]

array([[3, 4, 5]])

In [51]:
 a = np.array([[(1,2,3),(1,1,1),(2,2,2)],[(4,5,6),(2,2,2),(1,1,1)],[(5,6,7),(3,3,3),(3,3,3)],[(3,4,5),(4,4,4),(4,4,4)]])
>>> a

array([[[1, 2, 3],
        [1, 1, 1],
        [2, 2, 2]],

       [[4, 5, 6],
        [2, 2, 2],
        [1, 1, 1]],

       [[5, 6, 7],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 4, 5],
        [4, 4, 4],
        [4, 4, 4]]])

In [63]:
 a[0,0:3:2 ]

array([[1, 2, 3],
       [2, 2, 2]])

In [66]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
...                 [ 10, 12, 13]]
               
               ,
...                [[100,101,102],
...                 [110,112,113]]])
>>> c.shape

(2, 2, 3)

In [67]:
 c[0,...]                                   

array([[ 0,  1,  2],
       [10, 12, 13]])